logging:
  level:
   org:
    springframework:
     security: DEBUG

wenflon:
  complex-conditions:
    allPetPharmacy:
      allOf:
        petClassificatorProvider:
          values: domestic_small
        chipInfoProvider:
          lessThan: 7
    healthyPets:
      anyOf:
        petClassificatorProvider:
          values: domestic_small, domestic_large, wild
        chipInfoProvider:
          rangeClosed: 7, 20
#    oldDogDrugs: //todo temp, will make work on 2 and then "following the instruction" try to add the third one
#      allOf:
#        petClassificatorProvider:
#          values: dog
#        chipInfoProvider:
#          moreThan: 20