logging:
  level:
   org:
    springframework:
     security: DEBUG

wenflon:
  complex-conditions:
    allPetPharmacy:
      allOf:
        europeanPetClassificator:
          values: panda, dog, guinea pig, chupakabra
        chipInfoService:
          lessThan: 7
    healthyPets:
      anyOf:
        europeanPetClassificator:
          values: duck, cat, dog
        chipInfoService:
          rangeClosed: 7, 20
#    oldDogDrugs: //todo temp, will make work on 2 and then "following the instruction" try to add the third one
#      allOf:
#        europeanPetClassificator:
#          values: dog
#        chipInfoService:
#          moreThan: 20